### ISSUE TITLE
Mention + document other runners

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp2040-project-template#16]
Currently assume everyone wants probe-run.
Need to add how-to if for other runners to the docs, .cargo/config etc
elf2uf2 is added to the docs in https://github.com/rp-rs/rp2040-project-template/pull/14

**Comment by 9names** [comment]
Added configuration and docs for cargo-embed with #28.
Added configuration for probe-rs-debugger with #29

**Comment by jannic** [comment]
You added information about alternative runners to the README in https://github.com/rp-rs/rp2040-project-template/pull/19. Does that fix this issue, or do you want to add more documentation?

**Comment by 9names** [comment]
My goal was to cover openocd/pyocd as well, but I quickly realised that it's too much to explain.
To be quite honest, I think we need to create an RP2040/W book and evict basically all docs from this repo. Maybe we can do that *and* deprecate this repo in favour of one without the fluff at the same time?

In the meantime: I fixed up a few more errors in the cargo-embed instructions + added `probe-rs-cli run` versions in #49, those are brief enough that I think we can afford to have them here for now.

**Comment by jannic** [comment]
> To be quite honest, I think we need to create an RP2040/W book

There is still a lot of room for improvement, yes! But let's keep the existing documentation correct & up to date before we start a big new project.

Also, I prefer having basic documentation close to the code. It's perfectly fine to omit more complex details or alternative approaches, and refer to some central documentation instead, to avoid too much duplication. But the READMEs of individual crates should contain enough information to get started.

**Comment by jhodapp** [comment]
> My goal was to cover openocd/pyocd as well, but I quickly realised that it's too much to explain. To be quite honest, I think we need to create an RP2040/W book and evict basically all docs from this repo. Maybe we can do that _and_ deprecate this repo in favour of one without the fluff at the same time?

If it's worth anything to these efforts, please feel free to [take from the OpenOCD guide that I wrote here](https://reltech.substack.com/p/getting-started-with-rust-on-a-raspberry). I've tried keeping it relatively up to date but realize it may not be right now. So, feel free to take it or leave it.

**Comment by 9names** [comment]
@jhodapp Thanks for the offer! I might take you up on it.
I would want to strip it down to just the OpenOCD section and update it to use the CMSIS-DAP firmware and config to match how the official "Getting started guide" now does it
https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf#page=62

Upstream OpenOCD releases now supports rp2040 over CMSIS-DAP, which should simplify the installation instructions even compared to the Pico guide.

**Comment by jhodapp** [comment]
@9names thats great to know, I haven't tracked the latest here so I appreciate you letting me know upstream changed.
