### ISSUE TITLE
repo / crate name

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp2040-project-template#17]
This was originally intended to be used like https://github.com/knurling-rs/app-template, so an end-user would create a new project from this repo using cargo-generate and it would rename the crate, add authors, etc
That's not how it currently works - and I'm not sure we even want that.
Beginners are way more likely to clone/download this repo and then wonder why nothing works if they needed to run cargo-generate.
And not everyone is comfortable around the terminal, we should want to support IDE-only users..

So maybe this should be named rp2040-quickstart, or something more accurate and obvious.

**Comment by corvus-ch** [comment]
How about both: cago generate and simple download?

This could be achieved with a GitHub action generating a generic but functional archive and making it available in the releases section. 

Console savi people then can just use cargo generate. The others can download a template archive and start working from that. Instructions in the Readme will help understand what the options are. 

I can contribute such a GitHub action. But before I invest time, I would like to know if this is in the interest of the ones maintaining this template.

**Comment by 9names** [comment]
I really want to keep this as simple as possible for non-tech-savvy people to pick up.
I don't think an action that creates an archive in `Releases` would accomplish that as well as the current setup does.

Back when I wrote this issue originally, `cargo-generate` did not have the scripting support it currently has.
With this new functionality we should be able to support cargo-generate without breaking the current user experience I think. That would be my preferred approach to improving this template.

**Comment by 9names** [comment]
now that #65 is merged you can generate a template using
```system
cargo generate gh:rp-rs/rp2040-project-template -n my-cool-project
```
not closing this issue yet, as it is really about the name of this repo and not cargo-generate support.

**Comment by 9names** [comment]
After 3 years of it being called rp2040-project-template, I think there's more value in keeping it the same than there will ever be in changing it - I personally don't want to break existing tutorials and teaching materials.
If anyone else wants to change the name, make a new PR and link back to this one.
