### ISSUE TITLE
Flash problem

### ISSUE THREAD

**Issue by simeondmr** [rp-rs/rp2040-project-template#24]
Hello,

I'm using windows 10 and I have this problem:

```
cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.11s
     Running `probe-run --chip RP2040 'target\thumbv6m-none-eabi\release\rp2040-project-template'`
(HOST) WARN  (BUG) location info is incomplete; it will be omitted from the output
Error: no probe was found.

Common reasons for this are faulty cables or missing permissions.
For detailed instructions, visit: https://github.com/knurling-rs/probe-run/tree/2f138c3#troubleshooting
error: process didn't exit successfully: `probe-run --chip RP2040 'target\thumbv6m-none-eabi\release\rp2040-project-template'` (exit code: 1)
```

could you help me?

Thanks!

**Comment by 9names** [comment]
Which [debug probe](https://github.com/rp-rs/rp2040-project-template/blob/main/debug_probes.md) are you using? How is it connected?

If you aren't using a debug probe, you'll need to follow the instructions from [the readme](https://github.com/rp-rs/rp2040-project-template#alternative-runners) on how to program your rp2040 without one.

**Comment by simeondmr** [comment]
Hello,

I'm not using a debug probe at the moment.
I will try the instructions from https://github.com/rp-rs/rp2040-project-template#alternative-runners this evening and I will update you.

Thanks for your time.

**Comment by simeondmr** [comment]
Thanks a lot, it work perfectly!
Have a good day!!
