### ISSUE TITLE
Debug support via probe-rs-debugger

### ISSUE THREAD

**Issue by UnicornsOnLSD** [rp-rs/rp2040-project-template#26]
I'm trying to set up probe-rs-debugger with VSCode to easily set breakpoints and debug my program. Would it be possible for a probe-rs-debugger config to be created for this template?

**Comment by 9names** [comment]
Hi, I've added a config to a PR that is working for me, could you test it out?

Use alpha 0.4.0 and install instructions from here:
https://github.com/probe-rs/vscode/releases
