### ISSUE TITLE
when trying to build or run template: rust-lld: error: memory.x:2: region 'BOOT2' already defined 

### ISSUE THREAD

**Issue by osimmac** [rp-rs/rp2040-project-template#30]
im on fedora linux 5.17, just trying to get a template running to get started but i keep running into this error, can't figure out how to fix it:''

>note: rust-lld: error: memory.x:2: region 'BOOT2' already defined
>          >>>     BOOT2 : ORIGIN = 0x10000000, LENGTH = 0x100
>          >>>                                           ^
>         
>          flip-link: the native linker failed to link the program normally; please check your project configuration and linker scripts

the only thing i altered was the .cargo/config.toml, commenting out the probe-run and uncommenting the elf2uf2 runner. i have all the prerequisites installed.

**Comment by 9names** [comment]
that's strange. which version of rust are you running?
the usual issue that people run into is related to having RUSTFLAGS defined elsewhere (either in their environment variables, or $HOME/.cargo), could you check that?
the only other thing i can think of is that cargo looks up the directory tree for cargo.toml and workspace files - if you haven't tried already, could you try checking into a new path (a checkout to /tmp/rp2040-project-template should suffice)

**Comment by osimmac** [comment]
clearing come config files that i put in the wrong place did the trick (i misunderstood and was placing files in $HOME/.cargo/)

**Comment by mfp20** [comment]
> 
>   = note: some arguments are omitted. use `--verbose` to show all linker arguments
>   = note: rust-lld: error: memory.x:2: region 'BOOT3' already defined␍
>           >>>     BOOT3 : ORIGIN = 0x10000000, LENGTH = 0x100␍
>           >>>                                           ^␍
> 
>           flip-link: the native linker failed to link the program normally; please check your project configuration and linker scripts
> 

Same here. Courious fact: I changed all occurrences of "BOOT2" in memory.x file, with "BOOT3" and the same error appeared (as you can see above, it says "BOOT3" instead of "BOOT2"). It looks like the same step in the build process it is run twice.

I'm on Windows and I reinstalled all rust more than twice, checking every time there was nothing in $HOME/.cargo. I'm new to rust so I'm having hard time to troubleshoot.

**Comment by 9names** [comment]
@mfp20 please open a new issue that references this one, instead of commenting on a closed issue.
