### ISSUE TITLE
Linking: Can't compile

### ISSUE THREAD

**Issue by yallxe** [rp-rs/rp2040-project-template#33]
```
error: linking with `flip-link` failed: exit code: 1
  |
  = note: "flip-link" "-flavor" "gnu" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\deps\\rp2040_project_template-1198b80032431cff.rp2040_project_template.9c75850d-cgu.0.rcgu.o" "--as-needed" "-L" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\deps" "-L" "D:\\Dev\\rp2040-project-template\\target\\release\\deps" "-L" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\build\\rp2040-project-template-ff201362c93239a8\\out" "-L" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\build\\cortex-m-edb3200537960378\\out" "-L" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\build\\cortex-m-rt-44339646bd76ccef\\out" "-L" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\build\\defmt-4ae0c0a354199f32\\out" "-L" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\build\\rp2040-pac-6d37e37f505878c4\\out" "-L" "C:\\Users\\yallxe\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv6m-none-eabi\\lib" "-Bstatic" "C:\\Users\\yallxe\\AppData\\Local\\Temp\\rustcxHD7yj\\libcortex_m_rt-de909aa96899d9be.rlib" "--start-group" "C:\\Users\\yallxe\\AppData\\Local\\Temp\\rustcxHD7yj\\libcortex_m-f1aabfc11535f99f.rlib" "--end-group" "C:\\Users\\yallxe\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv6m-none-eabi\\lib\\libcompiler_builtins-8800918f309bcb9b.rlib" "-Bdynamic" "--eh-frame-hdr" "-znoexecstack" "-L" "C:\\Users\\yallxe\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv6m-none-eabi\\lib" "-o" "D:\\Dev\\rp2040-project-template\\target\\thumbv6m-none-eabi\\release\\deps\\rp2040_project_template-1198b80032431cff" "--gc-sections" "-O1" "--nmagic" "-Tlink.x" "-Tdefmt.x"
  = note: rust-lld: error: duplicate symbol: __aeabi_uidivmod
          >>> defined at rp2040_project_template.9c75850d-cgu.0
          >>>            D:\Dev\rp2040-project-template\target\thumbv6m-none-eabi\release\deps\rp2040_project_template-1198b80032431cff.rp2040_project_template.9c75850d-cgu.0.rcgu.o:(.text+0x1)
          >>> defined at arm.rs:14 (/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.66/src\arm.rs:14)
          >>>            compiler_builtins-8800918f309bcb9b.compiler_builtins.14216641-cgu.174.rcgu.o:(.text.__aeabi_uidivmod+0x1) in archive C:\Users\yallxe\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\thumbv6m-none-eabi\lib\libcompiler_builtins-8800918f309bcb9b.rlib
          
          rust-lld: error: duplicate symbol: __aeabi_idivmod
          >>> defined at rp2040_project_template.9c75850d-cgu.0
          >>>            D:\Dev\rp2040-project-template\target\thumbv6m-none-eabi\release\deps\rp2040_project_template-1198b80032431cff.rp2040_project_template.9c75850d-cgu.0.rcgu.o:(.text+0x35)
          >>> defined at arm.rs:82 (/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.66/src\arm.rs:82)
          >>>            compiler_builtins-8800918f309bcb9b.compiler_builtins.14216641-cgu.174.rcgu.o:(.text.__aeabi_idivmod+0x1) in archive C:\Users\yallxe\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\thumbv6m-none-eabi\lib\libcompiler_builtins-8800918f309bcb9b.rlib
          
          flip-link: the native linker failed to link the program normally; please check your project configuration and linker scripts
          
```
Getting this error very often, but sometimes it manages to compile and flash successfully.

**Comment by 9names** [comment]
I have never seen this error before! Could you provide any further information than this?
Obviously you're running on windows, but is this windows 10 or 11? is it in a virtual machine?
Is D: a local drive, a network drive or a USB drive?
When you say "very often" do you mean once a day, one in 10 compiles, every second compile?

**Comment by yallxe** [comment]
I was using Windows 10 with my main physical non-virtual machine, D: is a local drive and by saying "very often" I mean that it **may** compile and flash successfully, but for unknown reason, the next day it may begin showing this error.

**Comment by yallxe** [comment]
I also tried delete **my edited template with my code**, redownload the template and try to compile and flash the new fresh template.

Moreover, sometimes changing `cargo run` to `cargo run --release` helped, but I'm pretty sure it's not the fix because with `--release` the error still appears sometimes.

**Comment by 9names** [comment]
Thanks for the extra info. I haven't been able to reproduce it locally yet, but at least you've ruled out a few things.
Also, found some issues on compiler-builtins that seem to indicate that things aren't working as expected here.
https://github.com/rust-lang/compiler-builtins/issues/412

Could you try removing the `codegen-units` lines from your Cargo.toml, maybe forcing `codegen-units = 1` is causing it to do the wrong thing...

**Comment by mclane** [comment]
As mentioned in https://github.com/rust-lang/compiler-builtins/issues/412 switching to the nightly version of the rust compiler resolved the problem here.

**Comment by 9names** [comment]
> As mentioned in [rust-lang/compiler-builtins#412](https://github.com/rust-lang/compiler-builtins/issues/412) switching to the nightly version of the rust compiler resolved the problem here.

Were you having this problem as well?

**Comment by mclane** [comment]
Yes, I had the same problem (Manjaro Linux)

**Comment by 9names** [comment]
Hmm, yallxe was already using a nightly compiler though? Was it an old one?
They were getting built against compiler_builtins-0.1.66, but the version with the fix was  compiler_builtins-0.1.69
And the current stable should be using a newer version than that too...

**Comment by 9names** [comment]
I've created an issue on the HAL since this is not a template bug.
I'd like it if the discussion continued there please.

**Comment by yallxe** [comment]
I tried to reinstall rust on my PC, seems to work for now on nightly.

**Comment by 9names** [comment]
I'm going to assume the issue was an old nightly compiler, and this issue has been resolved by updating.
Mind closing this issue if it has been resolved?

**Comment by yallxe** [comment]
I think the compiler was the issue, but, everything seems to work now so I will close the issue. Thank everybody for the help
