### ISSUE TITLE
Mention Picoprobe CMSIS-DAP firmaware

### ISSUE THREAD

**Issue by elpiel** [rp-rs/rp2040-project-template#40]
There's a new firmware for picoprobe that can be used with probe-run:

https://github.com/raspberrypi/picoprobe/releases/tag/picoprobe-cmsis-v1.0.1

I've been running it for some time now and works flawlessly.

**Comment by 9names** [comment]
We already do that:
![image](https://user-images.githubusercontent.com/60134748/219596100-2363aed1-bd6d-49f7-9d6f-5469f0d94bdb.png)
and that page is
![image](https://user-images.githubusercontent.com/60134748/219596203-7b211ad0-0f2c-4633-94db-db0b823c13b4.png)

This is directly below the table of contents.

**Comment by elpiel** [comment]
Ahhh... my bad. I somehow overlooked that it mentions CMSIS-DAP debug probes :sweat_smile: .
Awesome and thanks for your time!
