### ISSUE TITLE
cargo-embed not supposed to be used as runner

### ISSUE THREAD

**Issue by mike-kfed** [rp-rs/rp2040-project-template#45]
right now in the `.cargo/config.toml` there is a preconfigured runner for using `cargo embed`

however calling `cargo run --release` doesn't work as, quoting the Cargo docs:

> ... will be executed by invoking the specified runner with the actual executable passed as an argument

it breaks because `cargo embed` expects the config section as the only argument but it gets the path to the binary which doesn't match the `default` config section name. I suggest removing the runner from the cargo-config and adding "cargo-embed can be used" to the README.md.

**Comment by jannic** [comment]
Good point! `cargo-embed` is already mentioned in README.md, so I think it can just be removed from `.cargo/config.toml`
