### ISSUE TITLE
Failed to get information for AP ApAddress

### ISSUE THREAD

**Issue by teamplayer3** [rp-rs/rp2040-project-template#5]
Running template:
```
cargo run
```

Used second Pico as probe. Set it up like it states in the readme. How must the target one be set up?

Got following error:
```Bash
Error: Failed to get information for AP ApAddress { dp: Multidrop(1002927), ap: 0 }

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: hid_write
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: hid_write
  11: BaseThreadInitThunk
  12: RtlUserThreadStart
error: process didn't exit successfully: `probe-run-rp --chip RP2040 target\thumbv6m-none-eabi\debug\rp2040-project-template` (exit code: 1)
```

**Comment by D1plo1d** [comment]
I'm encountering the same error, does the target need to be plugged in to USB or is power provided over the debugger pins some how?

**Comment by D1plo1d** [comment]
To answer my own question: yes, the target needs to be plugged into USB.

**Comment by Erik1000** [comment]
> To answer my own question: yes, the target needs to be plugged into USB.

It actually does not have to be connected via USB for power. It can get it's power from the probe pico if you connect VSYS.

**Comment by Erik1000** [comment]
> Added a pinout in #6.

@jonathanpallant are you sure the Pin layout in the debug_probes.md is correct? I think GPIO 3 is ground. I set it up this way and had a hard time (didn't work, same error as in the issue title). For me it works if SWCLK goes into GPIO 4 and SWDIO goes into GPIO 5. This is the same setup as in the graphic @9names sent. GPIO 3 can be used for ground of course.

If it is indeed wrong, would you consider updating it and maybe adding the graphic from @9names (if they agree)?

**Comment by 9names** [comment]
Pin 3 on the Pico is GND. Pin 4 is GPIO3, which is labelled "GP3" on the bottom of the Pico and on the pinout diagram for the Pico, so I think debug_probes.md is technically correct.

**Comment by Erik1000** [comment]
True, you're right. It is indeed technically correct. Maybe add the graphic anyway to avoid potential confusion?
