### ISSUE TITLE
newer defmt & probe-run versions

### ISSUE THREAD

**Issue by elpiel** [rp-rs/rp2040-project-template#56]
What is the issue causing newer than versions of defmt (> 0.3.2) and probe-run (> 0.3.5) to fail flash the device?

**Comment by jannic** [comment]
Bugs / incompatible changes in defmt and probe-run.
Here are some explanations: https://github.com/rp-rs/rp-hal/issues/581

**Comment by elpiel** [comment]
Even with older or newer version of probe-run & defmt I'm unable to flash my device:


`probe-run 0.3.6`
`defmt =0.3.2`
```
Error: A ARM specific error occured.

Caused by:
    0: An error occured in the communication with an access port or debug port.
    1: Target device did not respond to request.

```

**Comment by elpiel** [comment]
It seems that even when directly connecting to the laptop and holding the BOOTSEL the pico doesn't show up in the file explorer.

Last time I used it it was working fine, I wonder what broke it...

Is there a way to see what's wrong with given RP pico?

**Comment by jannic** [comment]
> Is there a way to see what's wrong with given RP pico?

That's a difficult question. With embedded devices, if the chip appears dead, there are a lot of possible reasons. Of course it may actually be broken. But often it's just bad cabling (especially when you are using a breadboard).

For the pico, if you only connect the USB cable, hold BOOTSEL when plugging it in, and it still doesn't work, it could still be some software issue on your computer. What OS are you using? Known good USB cable? But at that point, I'd seriously consider a broken pico as a possible explanation.

**Comment by elpiel** [comment]
Yep, I tried 2 different data cables and holding BOOTSEL when plugging in into the laptop.

I'm using Ubuntu it has always shown up until now.

I'll try another PICO tomorrow and retry this one just to be sure.

**Comment by elpiel** [comment]
It was a bad breadboard. When I've previously removed the RP pico from the breadboard I must have damaged (bent) some of the rails inside.
