### ISSUE TITLE
Bare template crashes during release build with lto = 'fat' in nightly

### ISSUE THREAD

**Issue by skrb-io** [rp-rs/rp2040-project-template#71]
Building the rp2040 project template without any alterations with rust nightly results in an error caused by lto = 'fat' optimization

```
~/Documents/Projects/rp2040-nightly (main) $ cargo build --release
   Compiling rp2040-nightly v0.1.0 (/home/--/Documents/Projects/rp2040-nightly)
warning: Linking globals named '__addsf3': symbol multiply defined!

error: failed to load bitcode of module "rp2040_hal-33611457b63b1605.rp2040_hal.80f0522449fd3a4f-cgu.0.rcgu.o": 

warning: `rp2040-nightly` (bin "rp2040-nightly") generated 1 warning
error: could not compile `rp2040-nightly` (bin "rp2040-nightly") due to previous error; 1 warning emitted
```

It is possible that I am missing something, but changing lto = 'thin' seems to solve the issue albeit resulting in a larger binary size.

**Comment by jannic** [comment]
I bisected this build error using cargo-bisect-rustc. The first bad commit was 8c2b57721728233e074db69d93517614de338055. https://github.com/rust-lang/rust/issues/118559 reports a regression in that commit that matches ours well enough that I assume it's the same issue.

**Comment by ithinuel** [comment]
Indeed, and there seem to be a PR attempting to fix something relate: https://github.com/rust-lang/rust/pull/118568

With a bit a luck it might be fixed in the next couple of days.

**Comment by ithinuel** [comment]
Checked with stable, beta & nightly. This is now resolved. 🎉
