### ISSUE TITLE
Make clear how to control the onboard LED of the Pico W through the WiFi chip

### ISSUE THREAD

**Issue by JonathanLindsey** [rp-rs/rp2040-project-template#72]
#43 added a comment about the Pico W having the onboard LED connected to the WiFi chip but it is unclear how to actually control the onboard LED on the Pico W.

**Comment by jannic** [comment]
Well, currently you don't at least not with the rp2040-hal. You need a driver for the wifi chip.
You can do it with embassy: https://github.com/embassy-rs/embassy/blob/main/examples/rp/src/bin/wifi_blinky.rs

**Comment by JonathanLindsey** [comment]
Thanks!

**Comment by JonathanLindsey** [comment]
Thanks! Would it be worth documenting this in the code comment?
