### ISSUE TITLE
Update to get boot2 from BSP

### ISSUE THREAD

**Issue by thejpster** [rp-rs/rp2040-project-template#9]
The BSPs can now optionally supply a boot2 block.

We should show how to do that, and add any changes to the linker script fragment that are required.

**Comment by 9names** [comment]
The template currently uses the HAL and boot2 directly.
Should we change it to target the Pico BSP and remove those?

I usually use an alias
```rust
use itsy_bitsy_rp2040 as bsp;
```
so that I only need to change the import in cargo.toml and that line, and the rest of the code just works as long as the pin/peripheral names line up.

**Comment by 9names** [comment]
We can definitely change the linker script - the new extern line does not affect building the old way.

**Comment by thejpster** [comment]
Yes I think most people would use a BSP. We could maybe include two with one commented out so it's obvious where the changes are required.

Pico is a good default. Maybe the Adafruit Pro Micro as the commented out alternative?

**Comment by 9names** [comment]
Sounds good to me. It's a much better default.
